#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Rb.Forms.Barcode.Droid.Resource", IsApplication=false)]

namespace Rb.Forms.Barcode.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public static int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public static int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050009
			public static int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public static int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public static int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public static int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public static int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public static int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public static int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public static int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public static int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public static int common_signin_btn_text_dark = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public static int common_signin_btn_text_light = 2131034123;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int common_ic_googleplayservices = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public static int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public static int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public static int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public static int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public static int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public static int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public static int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public static int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public static int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public static int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public static int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public static int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public static int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public static int common_signin_btn_text_pressed_light = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public static int adjust_height = 2131165184;
			
			// aapt resource value: 0x7f070001
			public static int adjust_width = 2131165185;
			
			// aapt resource value: 0x7f070003
			public static int contentFrame = 2131165187;
			
			// aapt resource value: 0x7f070002
			public static int none = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public static int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int zxingscanneractivitylayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int zxingscannerfragmentlayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040023
			public static int ApplicationName = 2130968611;
			
			// aapt resource value: 0x7f040022
			public static int Hello = 2130968610;
			
			// aapt resource value: 0x7f040001
			public static int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public static int common_android_wear_notification_needs_update_text = 2130968580;
			
			// aapt resource value: 0x7f040011
			public static int common_android_wear_update_text = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public static int common_android_wear_update_title = 2130968591;
			
			// aapt resource value: 0x7f04001f
			public static int common_google_play_services_api_unavailable_text = 2130968607;
			
			// aapt resource value: 0x7f04000d
			public static int common_google_play_services_enable_button = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public static int common_google_play_services_enable_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public static int common_google_play_services_enable_title = 2130968587;
			
			// aapt resource value: 0x7f040006
			public static int common_google_play_services_error_notification_requested_by_msg = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public static int common_google_play_services_install_button = 2130968586;
			
			// aapt resource value: 0x7f040008
			public static int common_google_play_services_install_text_phone = 2130968584;
			
			// aapt resource value: 0x7f040009
			public static int common_google_play_services_install_text_tablet = 2130968585;
			
			// aapt resource value: 0x7f040007
			public static int common_google_play_services_install_title = 2130968583;
			
			// aapt resource value: 0x7f040017
			public static int common_google_play_services_invalid_account_text = 2130968599;
			
			// aapt resource value: 0x7f040016
			public static int common_google_play_services_invalid_account_title = 2130968598;
			
			// aapt resource value: 0x7f040005
			public static int common_google_play_services_needs_enabling_title = 2130968581;
			
			// aapt resource value: 0x7f040015
			public static int common_google_play_services_network_error_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public static int common_google_play_services_network_error_title = 2130968596;
			
			// aapt resource value: 0x7f040003
			public static int common_google_play_services_notification_needs_update_title = 2130968579;
			
			// aapt resource value: 0x7f040002
			public static int common_google_play_services_notification_ticker = 2130968578;
			
			// aapt resource value: 0x7f040021
			public static int common_google_play_services_sign_in_failed_text = 2130968609;
			
			// aapt resource value: 0x7f040020
			public static int common_google_play_services_sign_in_failed_title = 2130968608;
			
			// aapt resource value: 0x7f040018
			public static int common_google_play_services_unknown_issue = 2130968600;
			
			// aapt resource value: 0x7f04001a
			public static int common_google_play_services_unsupported_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public static int common_google_play_services_unsupported_title = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public static int common_google_play_services_update_button = 2130968603;
			
			// aapt resource value: 0x7f040010
			public static int common_google_play_services_update_text = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public static int common_google_play_services_update_title = 2130968590;
			
			// aapt resource value: 0x7f040013
			public static int common_google_play_services_updating_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public static int common_google_play_services_updating_title = 2130968594;
			
			// aapt resource value: 0x7f04001e
			public static int common_open_on_phone = 2130968606;
			
			// aapt resource value: 0x7f04001c
			public static int common_signin_button_text = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public static int common_signin_button_text_long = 2130968605;
			
			// aapt resource value: 0x7f040024
			public static int library_name = 2130968612;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public static int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public static int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public static int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
